# Site settings
title: WNAG
email: tsmyfau@163.com
description: > # this means to ignore newlines until "baseurl:"
         Just a a blog to note these techniqual tips erevrday 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: wnag

# Build settings
markdown: kramdown
